### ISSUE TITLE
Icon width not working

### ISSUE THREAD

**Issue by RobinKuiper** [jcwillox/lovelace-paper-buttons-row#13]
I was testing some things with this component but I came to the conclusion that the width/height of an icon can't be changed. Whenever I change the with or height it just increases/decreases the container of the icon, but not the icon itself.

In the example below you can see it, I have put a border around it to better illustrate the problem.

https://i.imgur.com/k6wFkvQ.png

**Comment by jcwillox** [comment]
Yeah, I noticed this to the icon width is broken at the moment, I think this started with Home Assistant 0.110.0. They changed the way the `ha-icon` class works, now changing the width only affects the icon container, not the icon itself.

**Comment by jcwillox** [comment]
I had a quick look and it seems now you can use the `--mdc-icon-size` CSS variable to control the icon width. So instead of using width `width: 32px` use `--mdc-icon-size: 32px`

**Comment by RobinKuiper** [comment]
Works great, Thank you!
