### ISSUE TITLE
Button icon does not resize with buttons-> style -> icon -> width

### ISSUE THREAD

**Issue by altersis** [jcwillox/lovelace-paper-buttons-row#15]
**Browser + Version:**
Chrome Version 83.0.4103.106 (Official Build) (64-bit)

**Home Assistant release (hass --version):**
0.111.2

**Problem-relevant configuration.yaml entries:**

None. This is related only to the lovelace configuration. 

**Problem-relavant lovelace.yaml:**

>                   - entities:
                      - align_icons: top
                        buttons:
                          - entity: input_boolean.social_mode
                            name: Social
                            style:
                              button:
                                background-color: 'rgb(50,50,50);'
                                border-radius: 10px;
                                font-size: 18px;
                                width: 100px;
                              icon:
                                background-color: 'rgb(30,30,30);'
                                width: 70px;
                                height: 70px;
                                vertical-align: middle;
                          - entity: input_boolean.relax_mode
                            name: Relax
                            style:
                              button:
                                background-color: 'rgb(50,50,50);'
                                border-radius: 10px
                                font-size: 18px
                                width: 100px
                        type: 'custom:paper-buttons-row'

**Description:** 
Instructions say that in order to enlarge the icon, width and height need to be included as part of **icon** inside the **style** for a button row.  At least for me, only the space dedicated to the icon grows, but the icon itself stays the same size. See first icon "Social". Changed the backgroud to a lighter color to make this more evident. 

![image](https://user-images.githubusercontent.com/32140109/84705379-4c7cf900-af29-11ea-859b-c3b31ca0afc1.png)

My expectation is that the icon should resize to occupy the available space.

THanks!

**Comment by jcwillox** [comment]
I think #13 should have your answer 👍.

**Comment by altersis** [comment]
hey @jcwillox , thanks! I never crossed my mind to look at the closed issues. Just checked and it works! 
The only thing left is to **THANK YOU for your work,** buttons-row really makes it easier to produce much prettier UIs!

Cheers!

**Comment by jcwillox** [comment]
Thank you so much, it's really great to hear that 😃!
