### ISSUE TITLE
[request ]add tooltip functionality

### ISSUE THREAD

**Issue by miguelcaravantes** [jcwillox/lovelace-paper-buttons-row#17]
add option to add a tooltip for a button, useful when the control is using name: false

i think a simple title html tag can work pretty straightforward

![image](https://user-images.githubusercontent.com/17279582/87706330-f2a86280-c764-11ea-9ca6-ea407fad7342.png)

**Comment by jcwillox** [comment]
Great idea, it will also improve accessibility.
How do you propose we name the title?
My thought would be to pull the title from whatever the `name` option would be if it wasn't set to false.

**Comment by miguelcaravantes** [comment]
i was thinking 4 options

to keep the false behavior and use html tag name
```
name: false
title: text for tooltip
```

to keep the false behavior and use a more user friendly name
```
name: false
tooltip: text for tooltip
```

In this case we can keep accepting false to avoid break changes 
```
name: text for tooltip
only_icon: true
```


one last is accepting array in `name` property
```
name:
  - false
  - text for tooltip
```

`name: [false, text for tooltip]`

**Comment by jcwillox** [comment]
Great ideas, option 2 looks like the best, it's the most intuitive to users, has no breaking changes, and aligns best with Home Assistant's typical structure.
If `tooltip` is not set to false or a string (i.e. it is undefined) then the default tooltip can be based on the name or action. Home Assistant names the title based on the action.
![tooltip](https://user-images.githubusercontent.com/39120423/87878522-1818c300-ca28-11ea-9eb5-008edec32787.png)

**Comment by miguelcaravantes** [comment]
Sounds pretty good!!

**Comment by jcwillox** [comment]
This feature has been added in release [0.3.0](https://github.com/jcwillox/lovelace-paper-buttons-row/releases/tag/0.3.0) 🎉. I was actually able to directly copy this feature from Home Assistant's `computeTooltip` method, the only difference was they used `title` instead of `tooltip`.

**Comment by miguelcaravantes** [comment]
That's great i will try it!!! thank you so mush
