### ISSUE TITLE
Paper buttons action not working with browser_mod until visited in plain lovelace

### ISSUE THREAD

**Issue by Alfiegerner** [jcwillox/lovelace-paper-buttons-row#18]
Hi,

I'm attempting to use browser_mod with paper-buttons in a custom pop up but button presses do not work unless I visit a paper buttons populated card in vanilla lovelace first .

Any ideas on what I could try to get around this?  Also asking for assistance on browser_mod but thought to ask here in case you have any ideas.

Thanks,

Alex

**Comment by jcwillox** [comment]
Sounds like it might be a lazy loading issue, do the buttons show at all in the popup before visiting vanilla Lovelace?

**Comment by Alfiegerner** [comment]
Yep all the buttons appear and those with styling for states are correctly rendered. Just the action not triggering.

**Comment by jcwillox** [comment]
Right, seems like its related #16, however, I'm not really sure what's causing this, but I have some ideas that may fix it.
Would you mind sharing your config for the problem card/popup so I can test it, hopefully I will be able to reproduce this issue.

**Comment by Alfiegerner** [comment]
Awesome - thanks for your efforts.

Here's the popup in it's full glory. I'll have a look to see if I can produce a minimum reproducible config.

**Comment by jcwillox** [comment]
Thanks for that, I was able to test the popups, sadly I wasn't able to reproduce the issue.

For reference, I tested it with the latest version of HA, paper-buttons-row and browser_mod.
This is what the view looked like, however, I never had an issue getting the buttons to work.

![image](https://user-images.githubusercontent.com/39120423/88470986-80930300-cf46-11ea-8215-40c3fa8c1bbd.png)

**Comment by Alfiegerner** [comment]
Thanks for looking into it, much appreciated.

Doing some digging and it looks like the issue is that the 'action-handler' dom element has not been initialized on this page. 

I've been poking around what I'd need to get it in my custom card but running out of steam for tonight, if you have any thoughts am all ears.

Thanks.

![action-handler-null](https://user-images.githubusercontent.com/596188/88477318-3a17c580-cf93-11ea-92d5-92578325b9b2.PNG)

**Comment by jcwillox** [comment]
Oh wow, this is perfect, this validates my theory that the buttons weren't binding to the action handler correctly.
Seems like the solution is the include the action handler as part of paper-buttons-row, as some other plugins have done ([button-card](https://github.com/custom-cards/button-card/blob/master/src/action-handler.ts)), as a bonus, it will allow me to add new functionality such as repeating actions (#8).

**Comment by Alfiegerner** [comment]
Great, let me know if I can help.

Just as an FYI I've found that if I include a card that creates it's own action handler in my vertical stack then paper-buttons works fine.

So, e.g. having a card of type:light in the popup makes buttons responsive.

Entities card doesn't include action handler by default, (aside from for special row buttons) which is why it's absent in my pop up. May explain intermittent handler bugs depending on what cards have been rendered.

**Comment by jcwillox** [comment]
Yep that tracks, the action handler must be lazy loaded and home assistant only loads it when one of its internal cards requires it. Which I suspect was a recent'ish change and is why this issue is only popping up now.

Thanks for helping me get to the bottom of this.

**Comment by jcwillox** [comment]
Release [0.3.0](https://github.com/jcwillox/lovelace-paper-buttons-row/releases/tag/0.3.0) has just dropped, the action handler is now embedded within paper-buttons-row.
That change should hopefully fix this issue, let me know how it goes 👍

**Comment by Alfiegerner** [comment]
Looking good, and the repeat on hold is awesome! Thanks!
