### ISSUE TITLE
extend_paper_buttons_row with Mini Media Player

### ISSUE THREAD

**Issue by NovaGL** [jcwillox/lovelace-paper-buttons-row#19]
Great work you're doing.

The extend_paper_buttons_row is a neat feature but I just tried it with Mini Media Player as an entity and it doesn't work.

My aim is to hide everything but source in Mini Media Player and put the paper button row next to it.

**Comment by jcwillox** [comment]
Thanks, maybe I should clarify this in the docs, but the entity-row that you're extending must use the `generic-entity-row` element inside as that's the only element paper buttons row checks/supports. However, this covers most of the native entity rows (e.g. toggle, sensor, but not something like cast rows).

Custom entity-rows or in the case of `mini-media-player`, cards, aren't supported as they can use any internal structure and so we could not reliably insert the buttons. 
An alternate solution could be to use a horizontal-stack card, with some custom styling to make it invisible, [`stack-in-card`](https://github.com/custom-cards/stack-in-card) may work well for this.
