### ISSUE TITLE
Can't get base_config option to work successfully.

### ISSUE THREAD

**Issue by dozminic** [jcwillox/lovelace-paper-buttons-row#20]
Howdy!

I can't get the base_config option to work as described in the documentation. I've tried several different configurations, but I'm unable to have the configuration applied by default to all the buttons in a row. This is probably user error on my part, but I couldn't find any examples of anyone using it to inform my own configuration. Here is an example of one of the configurations I tried:

```type: entities
entities:
  - type: 'custom:paper-buttons-row'
    base_config:
      name: false
      icon: 'mdi:fire'
      style:
        button:
          background-color: red
          border-radius: 50%
    buttons:
      - entity: light.living_room
      - entity: light.living_room
        name: false
        icon: 'mdi:fire'
        style:
          button:
            background-color: red
            border-radius: 50%
```
I would expect the first entity to look like the second, but it does not. I suspect I'm using base_config incorrectly, and that the indentation above is incorrect, but I have tweaked it a number of different times without success. Can you provide a working example in the documentation or fix a code issue if, in fact, it turns out there is one? Thank you!

**Comment by jcwillox** [comment]
Well your config looks perfect, I copy and pasted it and it immediately worked, it may be worth checking you're on the latest version `0.3.0`. Try checking your browser console logs for any errors you'll also see the version printed out there.

**Comment by dozminic** [comment]
Whelp, I had 0.3.0 installed, but reinstalling it did the trick (not sure what was wrong). Thank you for the quick response and all your work on this plugin!
