### ISSUE TITLE
Plugin not found in HACS

### ISSUE THREAD

**Issue by bartn** [jcwillox/lovelace-paper-buttons-row#23]
I cannot find this plugin using HACS. Either I am doing something wrong or the installation instructions are too vague, as there it is not mentioned it is to be found in HACS, but the directory structure refers to it.

**Comment by jcwillox** [comment]
Well it's definitely there, try searching for "Paper Buttons Row", "jcwillox" or "lovelace-paper-buttons-row" should show up. Possibly all the repositories might not have been indexed yet if you just installed HACS?

**Comment by bartn** [comment]
Apologies, you are totally right @jcwillox. Is must have been terribly confused by the odd interface of HACS.
Keep up the good work.
