### ISSUE TITLE
state_styles and attributes (brightness) ?

### ISSUE THREAD

**Issue by bachy** [jcwillox/lovelace-paper-buttons-row#26]
Is it possible to customize the styles using attributes (e.g. brightness) instead of actual state (e.g. on/off)

**Comment by jcwillox** [comment]
This has been fixed in release [0.5.0](https://github.com/jcwillox/lovelace-paper-buttons-row/releases/tag/0.5.0). See the second example [here](https://github.com/jcwillox/lovelace-paper-buttons-row#secondary-info-object).
