### ISSUE TITLE
Feature request: entity_picture/button_image

### ISSUE THREAD

**Issue by davidrustingha** [jcwillox/lovelace-paper-buttons-row#27]
With MDI icons being limited in branded icons, you have to create them yourself. When entity_picture or button_image becomes an option you can load the pictures as icons and have cleaner looking buttons.

**Comment by jcwillox** [comment]
This has been added in [0.4.0](https://github.com/jcwillox/lovelace-paper-buttons-row/releases/tag/0.4.0) 🎉
