### ISSUE TITLE
show the state of the entity

### ISSUE THREAD

**Issue by JPOliveGit** [jcwillox/lovelace-paper-buttons-row#28]
i'm having an hard time to make is show the entity state, i have a sensor that show a percentage but it is does not show it in paper buttons row it only shows the name. can i show both? is it possible i was reading older posts but could not find what i was looking for. thanks

**Comment by jcwillox** [comment]
This has been fixed in release [0.5.0](https://github.com/jcwillox/lovelace-paper-buttons-row/releases/tag/0.5.0).
