### ISSUE TITLE
Center Alignment

### ISSUE THREAD

**Issue by Pronown** [jcwillox/lovelace-paper-buttons-row#29]
Is it possible to align an icon or text to the actual center? Top left right and bottom are missing this key position. I thought using false for icon or name would center the other, but it just makes it invisible. Maybe I'm missing something though? I am fairly new to AH.

**Comment by jcwillox** [comment]
Hmm should be possible, button elements are centered by default, but when multiple fields are visible the group is centered not a specific element. If you want the icon to be in the exact center and the text to be above you should be able to achieve that using CSS. Can you give a clearer example of what you're trying to achieve?

**Comment by jnmoneo** [comment]
Hi! Is there any way to align the state text on a button? 
When I define the button width, the state text is always aligned to the left, no matter I write text-align: center. 
Thank you!

**Comment by jcwillox** [comment]
To change the alignment of the button contents you can use `justify-content`, however, the content is now centered by default in the [1.0.0](https://github.com/jcwillox/lovelace-paper-buttons-row/releases/tag/1.0.0) release.

```yaml
styles:
  button:
    justify-content: center
    # justify-content: flex-start
```
