### ISSUE TITLE
Add vibrate/haptic feedback

### ISSUE THREAD

**Issue by bublikOff** [jcwillox/lovelace-paper-buttons-row#49]
Original HA cards and elements support vibrate/haptic feedback but paper-buttons-row does not on navigate action =((

**Comment by jcwillox** [comment]
Oh I wasn't aware of that, well it's very easy to remedy, should only be a 1 line change 👍

**Comment by bublikOff** [comment]
> Oh I wasn't aware of that, well it's very easy to remedy, should only be a 1 line change 👍
I'll be very grateful!

**Comment by jcwillox** [comment]
Do navigate actions actually trigger haptic feedback? I had a look at the codebase and tried it in the UI, it appears they only provide haptic feedback on failure, is that what you're talking about?

**Comment by bublikOff** [comment]
I do plan to use audio feedback on my wall panel.
I just replace navigator.vibrate to my own function which plays touch tone.
I do plan use paper buttons for navigation between views and I do hide side menu and header (original views navigation)
For the moment I do use own hack which monitors url change but it makes nose in situation which must not have touch fx sound. For eg if HA see movments in front of the door it play own "alert" sound and switches to video doorphone view and as we can guess it also plays touch sound =(((( ... I just want to play sound when I tap/click on any button. And as I do use paper buttons it would be nice to play touch sound as it does when it calls service.
It would be nice for eg if you add option for each button entity eg "vibrate: true" ... and it will not use global mechanism which calls "navigator.vibrate"  ... toggle, navigate and etc. 
As when I click button I dont mind it  calls service or just do navigation

**Comment by bublikOff** [comment]
Here is my audio feedback hack for HA
As my wall panel does not have vibration motor I use audio feedback 
```
(function (window, document)
{
    //
    var audioTouchFx = new Audio("data:audio/wav;base64,UklGRqQAAABXQVZFZm10IBAAAAABAAEARKwAAIhYAQACABAAZGF0YYAAAAAAANb+Hv/qAP4HwRHQFPoRawq9/KfrUfNS9C/gjdyK6Pr4hBBQBkL2KwtTJDgoAw9m+ifu6Olc9xoJRwEg4h/VQ+TgBDn+LedK8mYUNEiyMTgWdAkjD5YQjQKs8bnhqeTR5fHtmPQB+5sD7g7nF3cRmwkrAi//PP+A/w79ePyC/g==");
    var audioTouchFxPlay = debounce(() => audioTouchFx.play());
    var syncTimer = null;

    //
    audioTouchFx.volume = 0.25;

    //
    function debounce (func, timeout = 300)
    {
      let timer;
      return (...args) => 
      {
        clearTimeout(timer);
        timer = setTimeout(() => { func.apply(this, args); }, timeout);
      };
    }

    //
    function syncTimerFinished () { syncTimer = null }

    //
    function syncHandler (event)
    {
        if(syncTimer !== null) audioTouchFxPlay();
        else
        {
            clearTimeout(syncTimer);
            syncTimer = setTimeout(syncTimerFinished, 500);
        }
    };

    //
    history.pushState = (f => function ()
    {
        var ret = f.apply(this, arguments);
        window.dispatchEvent(new Event('pushstate'));
        window.dispatchEvent(new Event('locationchange'));
        return ret;
    })(history.pushState);

    //
    history.replaceState = (f => function ()
    {
        var ret = f.apply(this, arguments);
        window.dispatchEvent(new Event('replacestate'));
        window.dispatchEvent(new Event('locationchange'));
        return ret;
    })(history.replaceState);

    //
    window.addEventListener('popstate',() =>  window.dispatchEvent(new Event('locationchange')));
    window.addEventListener('locationchange', syncHandler)
    window.addEventListener('click', () => syncHandler('click'));
    window.addEventListener('touchstart', () => syncHandler('touchstart'));

    //
    window.navigator.vibrate = () => audioTouchFxPlay();
})(window, document);
```

**Comment by jcwillox** [comment]
This has been added in release [0.6.0](https://github.com/jcwillox/lovelace-paper-buttons-row/releases/tag/0.6.0)
