### ISSUE TITLE
state_icons doesn't reflect state: { attribute: foo }

### ISSUE THREAD

**Issue by QRPp** [jcwillox/lovelace-paper-buttons-row#51]
Scenario: `state: { attribute: foo }` is in use.
Problem: the primary entity state still gets resolved via `state_icons`, not the value of the `foo` attribute of the entity.

This IMHO is incorrect, or at least inconsistent: e.g., `state_styles` resolution (IMHO correctly) uses the value of the `foo` attribute of the entity.

**Comment by jcwillox** [comment]
Yep, this sounds like an oversight, `state_icons` should work the same as `state_styles`, I'll have a look into it.
