### ISSUE TITLE
Align all buttons to the right

### ISSUE THREAD

**Issue by sander76** [jcwillox/lovelace-paper-buttons-row#58]
Currently all buttons are spread out evenly across the `flex-box` class.
It would be great to have the option to align those buttons left or right. (I guess by setting the `justify-content` property)

**Comment by jcwillox** [comment]
Yeah, fair enough, I'll probably add a style property to the top level of the config to set styles on the flex-box. I think that's probably the best way to do it.

**Comment by sander76** [comment]
Thanks !

**Comment by j9brown** [comment]
I would find this feature useful too.  Thanks!

**Comment by jcwillox** [comment]
The latest release [1.0.0](https://github.com/jcwillox/lovelace-paper-buttons-row/releases/tag/1.0.0) now provides a global `styles` options which will affect the flex-box for each row.
```yaml
type: custom:paper-buttons-row
styles:
  justify-content: flex-start
```
