### ISSUE TITLE
is it possible add animation style to icon or text, for example icon blinking

### ISSUE THREAD

**Issue by Cuacco** [jcwillox/lovelace-paper-buttons-row#59]
is it possible add animation style to icon or text, for example icon blinking

**Comment by jcwillox** [comment]
Not that I know of as you can only set direct CSS properties on the buttons, so you can't insert something like an `@keyframes` section, but you may be able to do that with an external tool, I know [card-mod](https://github.com/thomasloven/lovelace-card-mod) would be able to do that.

I do plan to add an `extra_styles` option in the future that would allow that, and I could also add built-in support for some basic animations like blink.

**Comment by jcwillox** [comment]
I've added an `extra_styles` option for you to define your own animations and the blink and rotating styles are now builtin in [1.0.0](https://github.com/jcwillox/lovelace-paper-buttons-row/releases/tag/1.0.0).
