### ISSUE TITLE
Add text outside of the button

### ISSUE THREAD

**Issue by miberecz** [jcwillox/lovelace-paper-buttons-row#60]
Or make a button 'unclickable'.

My story is, that I'm migrating from Openhab to HA, and to make it painless for my family I want to recreate the Openhab interface. Closest thing I found so far is this project.

I want to achieve something like this:
![image](https://user-images.githubusercontent.com/13240971/136613638-3d48c7a4-595e-42d1-a544-7a1048cadc91.png)

So far I have managed to do this:
![image](https://user-images.githubusercontent.com/13240971/136613708-275f9161-e349-461f-b31e-6f57cc78ce92.png)

I can see that button alignment is already a request in #58 but how do I add text before my buttons?

**Comment by jcwillox** [comment]
Yep this is totally possible with some CSS, here's an example
