### ISSUE TITLE
Be able to have 'tap action' to fire multiple actions

### ISSUE THREAD

**Issue by Shaun-Harrison** [jcwillox/lovelace-paper-buttons-row#61]
I tried something like 

```
tap_action:
  - action: action1
  - action: action2
```

But none of the actions fire, would be good if we could have a button fire multiple actions if possible

**Comment by jcwillox** [comment]
Yeah, that syntax isn't supported, depending on what you're trying to achieve using a script might be the easiest option. While I think it's a good idea, I'm trying to keep the action handler as close to Home Assistant's built-in one, in particular, I'm using the action handler from [custom-card-helpers](https://github.com/custom-cards/custom-card-helpers). This is what [button-card](https://github.com/custom-cards/button-card) is also using. It might be possible to add that functionality but would probably require quite a bit of work.

**Comment by Shaun-Harrison** [comment]
Hello!

Yeah since opening this I've started using scripts to get around this, i've been able to do what I've needed so will close the issue

Thank you for the reply!
