### ISSUE TITLE
alignment issue within the button once width/height are defined

### ISSUE THREAD

**Issue by labactani** [jcwillox/lovelace-paper-buttons-row#75]
Hi,
I have noticed that if I define the width/height of a button and for that button I define layout:icon_name, then the elements (icon and name) are aligned to the left and the align command is ignored. This does not happen if I do not define dimensions...
Anyone else having the same issue?

thanks

**Comment by jcwillox** [comment]
I'll have to test this out later do you have an example config you could share to help reproduce the issue?

**Comment by labactani** [comment]
Sure,
here my code:
If I remove the line in bold, the width attribute, it works but then the size od the button changes according to the content.

type: custom:paper-buttons-row
base_config:
  style:
    button:
      background-color: var(--my_color2)
      border-color: rgba(152, 167, 185, 0.2)
      border-style: outset
      border-width: 1px
      border-radius: 10px
      box-shadow: 1px 1px 5px 0px rgb(12, 12, 14)
      font-size: 15px
      margin: auto
      **width: 80px**
    name:
      color: white
      align: center
      margin-left: auto
      margin-right: auto
    icon:
      align: center
buttons:
  - entity: group.luci_salotto
    name: SALONE
    style:
      button:
        font-size: 20px
        width: 100px
        height: 48px
    state_styles:
      'on':
        button:
          box-shadow: 1px 1px 2px 2px rgb(255, 215, 0)
          background: linear-gradient(to top, transparent 50%, gold 100%)
  - entity: light.micky
    icon: mdi:lightbulb-group
    name: Micky
    layout: icon_name
    state_styles:
      'on':
        button:
          box-shadow: 1px 1px 2px 2px rgb(255, 215, 0)
          background: linear-gradient(to top, transparent 50%, gold 100%)
        icon:
          color: gold
  - entity: light.standing
    icon: mdi:floor-lamp-outline
    name: Standing
    layout: icon_name
    state_styles:
      'on':
        button:
          box-shadow: 1px 1px 2px 2px rgb(255, 215, 0)
          background: linear-gradient(to top, transparent 50%, gold 100%)
        icon:
          color: gold
  - entity: light.strip
    icon: mdi:led-strip-variant
    name: Strip
    layout: icon_name
    state_styles:
      'on':
        button:
          box-shadow: 1px 1px 2px 2px rgb(255, 215, 0)
          background: linear-gradient(to top, transparent 50%, gold 100%)
        icon:
          color: gold

**Comment by jcwillox** [comment]
So, I think your main issue is that `align: center` or rather `align` is not valid CSS property.
From, what I can tell you want to center the button and text so adding
          `justify-content: center` to the button should do that for you.

```yaml
  style:
    button:
      # ...
      justify-content: center
      width: 80px
```

Center alignment on the button should probably be the default I might look into changing that.

To create a code block just surround the code using three backticks
````
```yaml
# code....
```
````

**Comment by labactani** [comment]
That would explain indeed :-) 
Thanks a lot for looking into it, works flawlessly now!!
