### ISSUE TITLE
Feature request: add repeat to long press

### ISSUE THREAD

**Issue by Alfiegerner** [jcwillox/lovelace-paper-buttons-row#8]
Hi,

Thanks for your work on this, looking to migrate from the old version.

Would you consider adding a repeat value to hold actions? This would repeat an action every X milliseconds while button is held. 

Inspiration taken from here: 

https://github.com/custom-cards/button-card/blob/master/src/action-handler.ts

This would allow using buttons to control things like volume and brightness more naturally. Holding the button increases / decreases incrementally, and releasing stupid the repetition of actions.

**Comment by jcwillox** [comment]
Thanks!
I agree this would be a very cool feature to have, but this plugin uses Home Assistant's built-in [action handler](https://github.com/home-assistant/frontend/blob/dev/src/panels/lovelace/common/directives/action-handler-directive.ts), and looking at the code it doesn't support any sort of repeat action, the button will actually only receive the hold event once you release the button, which makes this very difficult to implement without using our own modified action handler embedded into the plugin. Regardless I will look into adding this 👍

**Comment by Alfiegerner** [comment]
Ah I can see the bay would require some effort, thanks very much for looking into it.

**Comment by jcwillox** [comment]
This feature has been added in release [0.3.0](https://github.com/jcwillox/lovelace-paper-buttons-row/releases/tag/0.3.0) 🎉
