### ISSUE TITLE
Ripple effect changes when name is set to false.

### ISSUE THREAD

**Issue by Schoultzies** [jcwillox/lovelace-paper-buttons-row#87]
The ripple effect changes on buttons that have their name set to false. The normal effect looks great, covering the entire button. A button without a name but just an icon, seems to reduce the area of the effect with a hard edge. Ps, what an awesome addon!!!

**Comment by jcwillox** [comment]
I completely agree and release [2.0.0](https://github.com/jcwillox/lovelace-paper-buttons-row/releases/tag/2.0.0) has the ability to override the ripple shape using the `ripple` option.
